apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sentiment-api
  namespace: default
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: sentiment-api
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 10s